--- # My primer YAML Playbook for ansible

- hosts: all
  remote_user: awx
  #udo: yes
  #sudo_user: awx
  become: true
  connection: ssh
  gather_facts: no
  tasks:
  - name: Instalar telnet
    #become=true
    action: yum name=telnet state=present
    #action: ping
    #icome: yes
    #ecome_method: sudo
