---

- name: 1. Install MySQL server package
  yum: name=mariadb-server state=present

- name: 2. Start Mysql Service
  service: name=mariadb state=started enabled=true

#- name: Install python Mysql package #required for mysql_db tasks
#  apt: name=python-mysqldb state=present
#- name: 3. Install module Phtyon MySQL
#  pip: name=MySQL-python

- name: 3. Create a new database
  mysql_db: name=demo1 state=present collation=utf8_general_ci

- name: 4. Create a database user
  mysql_user: name=demo1 password=demo1 priv=*.*:ALL host=localhost state=present

- name: 5a. Copy sample data
  copy: src=dump.sql dest=/tmp/dump.sql

- name: 5b. Insert sample data
  shell: cat /tmp/dump.sql | mysql -u demo1 -pdemo1 demo1

- name: 6. Copiar fichero php
  copy: src=db.php dest=/var/www/html/db.php mode=0664



#- name: 6. Install MySQL extension for PHP
#  apt: name=php5-mysql state=present
