---

    - name: 1. Install Apache
      yum: name=httpd state=present

    - name: 2. install PHP module for Apache
      yum: name=php state=present

    - name: 3. Install module php-mysql
      yum: name=php-mysql state=present

    - name: 4. start Apache
      service: name=httpd state=started enabled=yes

#    - name: 4. install Hello World PHP script
#      copy: src=index.php dest=/var/www/html/index.php mode=0664
