---

- hosts: localhost
  connection: local
  tasks:
   - block:
        - name: Obtain SSO token
          ovirt_auth:
               url: https://plirhapli01/ovirt-engine/api
               username: admin@internal
               password: Andorra2016
               ca_file: /tmp/ca.pem
                
# Paramos máquina virtual para poder restaurar snapshot

        - ovirt_vms:
             auth: "{{ ovirt_auth }}"
             state: stopped
             name: "{{ namevm }} "


        - ovirt_snapshots:
               auth: "{{ ovirt_auth }}"
               state: restore
               vm_name: "{{ namevm }}"
               snapshot_id: "{{ id }}"
        - ovirt_vms:
             auth: "{{ ovirt_auth }}"
             state: running
             name: "{{ namevm }} "



     always:
      - name: Always revoke the SSO token
        ovirt_auth:
          state: absent
          ovirt_auth: "{{ ovirt_auth }}"
