---

- hosts: localhost
  tasks:
   - block:
        - include_vars: ovirt_password.yml
        - name: Obtain SSO token with using username/password credentials
          ovirt_auth:
            url: https://plirhapli01/ovirt-engine/api
            username: admin@internal
            ca_file: /tmp/ca.pem
            password: "{{ ovirt_password }}"


        - ovirt_vms:
           auth: "{{ ovirt_auth }}"
           state: absent
           name: myvm

     always:
      - name: Always revoke the SSO token
        ovirt_auth:
          state: absent
          ovirt_auth: "{{ ovirt_auth }}"
